### ISSUE TITLE
[Bug] Error command tambahutang

### ISSUE THREAD

**Issue by XCR90** [noaione/naoTimes#60]
**Jelaskan masalahnya**
Mohon tulis masalah yang dialami dengan jelas agar 

**Langkah reproduksi**
Jelaskan langkah untuk reproduksi:
1. Mengetik "!tambahutang"
2. Memasukkan ID "131565" untuk anime "takt op.Destiny"
3. Memasukkan perkiraan episode "12"
4. Mention staff yang dibutuhkan
5. Klik emoji "Check" "✅"

**Ekspektasi**
Hutang akan ditambah ke DB.

**Hal yang terjadi**
Error
Pesan bot N4O: Error: Insiden ini telah dilaporkan, mohon buka Issue baru di GitHub untuk mempercepat penyelesaian: https://github.com/naoTimesdev/naoTimes/issues/new/choose

**Info**
Guild ID: 808645869980221458
Channel ID: 808645872556179466
User ID: 271221589587001356

**Comment by noaione** [comment]
Sayangnya gak bisa tak cek kenapa masalahnya dikarenakan full fokus ke v3. Perkiraan v3 akan di deploy hari Sabtu nanti.

https://status.naoti.me/incident/17
